version: "3"

services:

  # Small sinatra app.
  json_notification_receiver:
    container_name: json_notification_receiver
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/json_notification_receiver
    ports:
      - "3001:3001"
    networks:
      - json_notification_receiver_network
    environment:
      # Sets environment type for sinatra.
      - APP_ENV=development
      # Sets environment type for servers: puma.
      - RACK_ENV=development
    command:
      [
        "/bin/sh",
        "-c",
        "bundle exec rackup config.ru --host 0.0.0.0 --port 3001"
      ]

networks:
  json_notification_receiver_network:
